# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-11 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20171112_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='forget_otp',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='user',
            name='forget_otp_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
