# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-03 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20171112_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deviceId',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
