# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-04 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180403_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qrhash',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
