# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-04 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_qrhash_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ismobile_loggedin',
            field=models.BooleanField(default=False),
        ),
    ]
