# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-01 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='account',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='account',
            name='treatment',
        ),
        migrations.AddField(
            model_name='account',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Appointment'),
        ),
    ]
