# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-02 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180601_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='updated',
            field=models.DateTimeField(null=True),
        ),
    ]
