# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-02 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_treatmentfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentfiles',
            name='file_description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
