# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-06 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_invoiceitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='net_cost',
        ),
        migrations.RemoveField(
            model_name='account',
            name='total_cost',
        ),
    ]
