# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-06 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180606_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='net_cost',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='account',
            name='total_cost',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
