# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-07 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180607_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_key', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='is_bill',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bill',
            name='estimate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Account'),
        ),
    ]
